import { supabase } from "@/lib/initSupabase"
import { Button } from "@chakra-ui/button"
import { Box, Center } from "@chakra-ui/layout"
import { Spinner } from "@chakra-ui/spinner"
import Head from "next/head"
import { useRouter } from "next/navigation"
import { useCallback, useEffect, useState } from "react"

export default function Home() {
  const [isLoading, setIsLoading] = useState(true)
  const [user, setUser] = useState(null)
  const { push } = useRouter()

  const signOut = async () => {
    setIsLoading(true)
    try {
      const { error } = await supabase.auth.signOut()
      console.log({ error })
      if (!error) {
        setUser(null)
      } else {
        console.error("error", error)
      }
    } catch (error) {
      console.error("error", error)
    } finally {
      setIsLoading(false)
    }
  }

  const fetchUser = useCallback(async () => {
    setIsLoading(true)
    try {
      const {
        data: { session },
      } = await supabase.auth.getSession()
      console.log({ session })
      setUser(session?.user || null)

      if (!session?.user) {
        push("/signin")
      }
    } catch (error) {
      console.error("error", error)
    } finally {
      setIsLoading(false)
    }
  }, [push])

  useEffect(() => {
    if (!user) {
      fetchUser()
    }
  }, [user, fetchUser])

  if (isLoading) {
    return (
      <Box pt={32}>
        <Center>
          <Spinner />
        </Center>
      </Box>
    )
  }

  return (
    <>
      <Head>
        <title>Food List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user?.email}
        <Button isLoading={isLoading} onClick={signOut}>
          Déco
        </Button>
      </main>
    </>
  )
}
