import { Recipes } from "@/contentPages/Recipes"
import Head from "next/head"

export default function FoodList() {
  return (
    <>
      <Head>
        <title>Food List - Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Recipes />
      </main>
    </>
  )
}
