import { SignUp } from "@/contentPages/SignUp"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Food List - Inscription</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignUp />
      </main>
    </>
  )
}
