import { SignIn } from "@/contentPages/SignIn"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Food List - Connexion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignIn />
      </main>
    </>
  )
}
